# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 185b613b8b912b42108ca8139ae169973b0606cafe5337b79d5e7745d9c658b4236ff1c9b25c3cd2334ec39027996836f35e04509e85e7c50fbe1d700429edde

test:
  secret_key_base: 56bd9a02debcbe506cec4d2523ff346ed822c1420f82c7a144295e1e43d9d822d3b7057f00be262d5d79306b71bbcc86308428c0564627ea63e7551b16628f3c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
